spring:
  application:
    name: mybatis-extend-demo
  datasource:
    username: health
    password: txYo71aRb
    url: jdbc:mysql://10.16.93.81:3306/test?serverTimeZone=Asia/Shanghai&characterEncoding=utf8
  mvc:
    logRequestDetails: true

logging:
  level:
    com:
      example:
        demo:
          mapper: debug
          controller: debug
          mbextend: debug