spring:
  application:
    name: mybatis-extend-demo
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.178.128:3306/test?serverTimeZone=Asia/Shanghai&characterEncoding=utf8
#  mvc:
#    logRequestDetails: true

#logging:
#  level:
#    com:
#      example:
#        demo:
#          mapper: debug
#          controller: debug
#          mbextend: debug